import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Nav from "../components/navigation/nav";
import Header from "../components/header/header";
import Sponsor from '../components/sponsor/sponsor';
import Services from '../components/Services/Services';
import Cost from '../components/cost/cost';
import Trial from '../components/trial/trial';
import HeroCard from '../components/heroCard/heroCard';
import Medel from '../components/medel/medal';
import Footer from '../components/footer/footer';
import Status from '../components/status/status';


import { sanityClient, urlFor } from "../lib/sanity";

const heroCardQuery = `*[_type == 'review']{
  _id,
  name,
  image,
  notes,
  bio[0]
}`;

const headerContainer = `*[_type == "header"]{
  name,
    _id,
  image,
  greeting
}`;

const SponsorContainer = `*[_type == "sponsor"]{
  name,
	_id,
  image,
}`;

const statusContainer = `*[_type == "status"]{
  name,
	_id,
  image,
}`;

const servicesContainer = `*[_type == "services"]{
  name,
	_id,
  image,
  heading,
  list1,
  list2,
  list3,
  list4,
}`;

const services2Container = `*[_type == "oddservices"]{
  name,
	_id,
  image,
  heading,
  list1,
  list2,
  list3,
  list4,
}`;
const services3Container = `*[_type == "thirdservices"]{
  name,
	_id,
  image,
  heading,
  list1,
  list2,
  list3,
  list4,
}`;
const services4Container = `*[_type == "fourthservices"]{
  name,
	_id,
  image,
  heading,
  list1,
  list2,
  list3,
  list4,
}`;
const services5Container = `*[_type == "fiveservices"]{
  name,
	_id,
  image,
  heading,
  list1,
  list2,
  list3,
  list4,
}`;
const services6Container = `*[_type == "sixservices"]{
  name,
	_id,
  image,
  heading,
  list1,
  list2,
  list3,
  list4,
}`;


export default function Home({ reviews, headers, Sponsors, myStatus, myServices, oddServices, servicesThree, services_four, services_fifth, services_six }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Bright Local App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main-home">
        <Nav />
        <Header headers={headers} />
        <Sponsor sponsor={Sponsors} />
        <Status status={myStatus} />
        <Services
          services={myServices}
          services2={oddServices}
          services3={servicesThree}
          services4={services_four}
          services5={services_fifth}
          services6={services_six}

        />
        <Cost />
        <Trial />
        <HeroCard props={reviews} />
        <Medel />
        <Footer />
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const reviews = await sanityClient.fetch(heroCardQuery);
  const headers = await sanityClient.fetch(headerContainer);
  const Sponsors = await sanityClient.fetch(SponsorContainer);
  const myStatus = await sanityClient.fetch(statusContainer);
  const myServices = await sanityClient.fetch(servicesContainer);
  const oddServices = await sanityClient.fetch(services2Container);
  const servicesThree = await sanityClient.fetch(services3Container);
  const services_four = await sanityClient.fetch(services4Container);
  const services_fifth = await sanityClient.fetch(services5Container);
  const services_six = await sanityClient.fetch(services6Container);
  return { props: { reviews, headers, Sponsors, myStatus, myServices, oddServices, servicesThree, services_four, services_fifth, services_six } };
}