import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NavBar from "../Components/Navigation/Nav";
import Header from "../Components/Header/Header";
import Sponsor from '../Components/Sponsor/Sponsor';
import Services from '../Components/Services/Services';
import Cost from '../Components/Cost/Cost';
import Trial from '../Components/Trial/Trial';
import HeroCard from '../Components/HeroCard/HeroCard';
import Medel from '../Components/Medel/Medel';
import Footer from '../Components/Footer/Footer';
import Status from '../Components/Status/Status';


import { sanityClient, urlFor } from "../lib/sanity";

const heroCardQuery = `*[_type == 'review']{
  _id,
  name,
  image,
  notes,
  bio[0]
}`;

const headerContainer = `*[_type == "header"]{
  name,
    _id,
  image,
  greeting
}`;

const SponsorContainer = `*[_type == "sponsor"]{
  name,
	_id,
  image,
}`;

const statusContainer = `*[_type == "status"]{
  name,
	_id,
  image,
}`;

const servicesContainer = `*[_type == "services"]{
  name,
	_id,
  image,
  heading,
  list1,
  list2,
  list3,
  list4,
}`;

const services2Container = `*[_type == "oddservices"]{
  name,
	_id,
  image,
  heading,
  list1,
  list2,
  list3,
  list4,
}`;
const services3Container = `*[_type == "thirdservices"]{
  name,
	_id,
  image,
  heading,
  list1,
  list2,
  list3,
  list4,
}`;
const services4Container = `*[_type == "fourthservices"]{
  name,
	_id,
  image,
  heading,
  list1,
  list2,
  list3,
  list4,
}`;
const services5Container = `*[_type == "fiveservices"]{
  name,
	_id,
  image,
  heading,
  list1,
  list2,
  list3,
  list4,
}`;

const services6Container = `*[_type == "sixservices"]{
  name,
	_id,
  image,
  heading,
  list1,
  list2,
  list3,
  list4,
}`;

const costService = `*[_type == "cost"]{
  name,
	_id,
  image,
  crossImg,
  list1,
  list2,
  list3,
}`;

const MedelData = `*[_type == "trial"]{
  name,
	_id,
  image,
	rating,
  starImg,
}`;


const FooterData = `*[_type == "footer"]{
  name,
	_id,
  list1,
  list2,
	list3,
  list4,
  list5,
  list6,
  list7,
  list8,
  list9,
  list10,
  list11,
  list12,
	list13,
  list14,
  list15,  
  list16,
}
`;

export default function Home({ reviews, headers, Sponsors, myStatus, myServices, oddServices, servicesThree, services_four, services_fifth, services_six, Cost_Service, Medels_Data, Footers_Data }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Bright Local Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <NavBar />
        <Header headers={headers} />
        <Sponsor sponsor={Sponsors} />
        <Status status={myStatus} />
        <Services
          services={myServices}
          services2={oddServices}
          services3={servicesThree}
          services4={services_four}
          services5={services_fifth}
          services6={services_six}
        />
        <Cost cost={Cost_Service} />
        <Trial />
        <HeroCard props={reviews} />
        <Medel Medel={Medels_Data} />
        <Footer footer={Footers_Data} />
      </>
    </div>
  )
}

export async function getStaticProps() {
  const reviews = await sanityClient.fetch(heroCardQuery);
  const headers = await sanityClient.fetch(headerContainer);
  const Sponsors = await sanityClient.fetch(SponsorContainer);
  const myStatus = await sanityClient.fetch(statusContainer);
  const myServices = await sanityClient.fetch(servicesContainer);
  const oddServices = await sanityClient.fetch(services2Container);
  const servicesThree = await sanityClient.fetch(services3Container);
  const services_four = await sanityClient.fetch(services4Container);
  const services_fifth = await sanityClient.fetch(services5Container);
  const services_six = await sanityClient.fetch(services6Container);
  const Cost_Service = await sanityClient.fetch(costService);
  const Medels_Data = await sanityClient.fetch(MedelData);
  const Footers_Data = await sanityClient.fetch(FooterData);
  return { props: { reviews, headers, Sponsors, myStatus, myServices, oddServices, servicesThree, services_four, services_fifth, services_six, Cost_Service, Medels_Data, Footers_Data } };
}